config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to: 'welcome#home'

  get 'brands', to: 'brands#show'
  get 'brands/:company/', to: 'brands#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def show
    @company = params[:company] if params[:company]

    respond_to do |format|
      format.js
      format.html { render :template => "welcome/home" }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_makingpretty.html.erb
<div class="page-header page-header--mp">
  <div class="container">
    <div class="page-logo"></div>
    <h1 class="text-title">makers of brands &amp; websites for the digital age</h1>
    <p class="text-note text--center">updated at</p>
  </div>
</div>

<div class="padding bg--white">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        <p class="text-caption">Pitch</p>
      </div>
      <div class="col-xs-12 col-sm-9">
        <p class="text-body">Hi there <span class="emoji">😊</span> – This page is used for design and development</p>
      </div>
    </div>
    <%= render 'brands/makingpretty/iconset' %>
  </div>
</div>

<section class="padding">
  <div class="container">
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Typography – Positive</h1>
        <p class="page-subtitle">Variants of black on white</p>
      </div>
    </div>
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <%= render 'brands/makingpretty/typography' %>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--dark">
  <div class="container">
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title--white">Typography – Negative</h1>
        <p class="page-subtitle--white">Variants of white on black/colour</p>
      </div>
    </div>
    <div class="row section--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <%= render 'brands/makingpretty/typography', color: 'white' %>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--white dev-button-variants">
  <style>.dev-button-variants .btn {margin-top: 5px;}</style>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Button Variants</h1>
        <p class="page-subtitle">Every Charlie Button</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <a href="#" class="btn">Default Button</a>
        <a href="#" class="btn btn--secondary">Secondary Button</a>
        <a href="#" class="btn btn--dark">Dark Button</a>
        <a href="#" class="btn btn--ghost">Ghost Button</a>
        <a href="#" class="btn btn--ghost-white">Ghost Button</a>
        <a href="#" class="btn btn--disabled">Disabled button</a>
        <a href="#" class="btn btn--secondary btn--disabled">Disabled button</a>
      </div>
    </div>
    <div class="row padding">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h2 class="text-lead text--center">Button special hover states:</h2>
        <a href="#" class="btn btn--to-danger">to danger</a>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title--white">Icon Set</h1>
        <p class="page-subtitle--white">Icons on black</p>
      </div>
    </div>
    <section class="text--white padding">
      <%= render 'brands/makingpretty/iconset', color: 'white' %>
    </section>
  </div>
</section>
<section class="padding">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Icon Set</h1>
        <p class="page-subtitle">Icons on white</p>
      </div>
    </div>
    <section class="padding">
      <%= render 'brands/makingpretty/iconset' %>
    </section>
  </div>
</section>

app/views/brands/makingpretty/_iconset.html.erb
<div class="row padding--top">
  <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
    <h2 class="text-lead<%= '--white' if defined? color %> text--left">Social and contact Icons</h2>

    <%= svg_icon('anim__mobile-menu') %>
    <%= svg_icon('anim__mobile-menu', file: 'iconanim.svg') %>
    <%= svg_icon('social__facebook', file: 'iconset.svg') %>
    <%= svg_icon('social__linkedin') %>
    <%= svg_icon('social__twitter') %>
    <%= svg_icon('social__phone') %>
    <%= svg_icon('social__email') %>
    <%= svg_icon('social__chat') %>

    <%= svg_icon('missing this one') %>
    <%= svg_icon('social__chat', class: 'icon--app') %>
    <%= svg_icon('social__linkedin', role: 'presentation') %>
    <%= svg_icon('social__facebook', aria: false) %>
  </div>
</div>
<div class="row padding--top">
  <div class="col-xs-12">
    <%= each_svg_icon %>
  </div>
</div>

app/views/brands/makingpretty/_typography.html.erb
<h1 class="page-title<%= '--white' if defined? color %> text--left">Header 1 – page-title</h1>
<p class="page-subtitle<%= '--white' if defined? color %> text--left">page-subtitle</p>

<h2 class="section-title<%= '--white' if defined? color %> text--left">Header 2 – section-title</h2>

<h3 class="text-title<%= '--white' if defined? color %>">Header 3 – text-title</h3>

<h4 class="text-subtitle<%= '--white' if defined? color %>">Header 4 – text-subtitle</h4>

<h5 class="text-lead<%= '--white' if defined? color %>">Header 5 – text-lead</h5>
<p class="text-lead<%= '--white' if defined? color %>">Text-lead – First and foremost, every line of code in Charlie has been written with your security in mind. We used the very latest framework releases, re-used tried and tested modules, and apply fundamental security considerations in every aspect of the software design.</p>

<h6 class="text-body<%= '--white' if defined? color %>">Header 6 – text-body</h6>
<p class="text-body<%= '--white' if defined? color %>">Text-body – Charlie forces HTTPS for everything, including on our public website. SSL (Secure Sockets Layer) and TLS (Transport Layer Security) are mechanisms for safely transmitting data. The SSL protocol is both outdated and insecure, and has since been replaced by TLS. However, the term “SSL” continues to be colloquially used, referring to a general mechanism for protecting transmitted data.</p>
<p class="text-body<%= '--white' if defined? color %>">Connection with Charlie are encrypted and authenticated using AES-128 and uses ECDHE as the key exchange mechanism.</p>
<p class="text-body<%= '--white' if defined? color %>">SSL and TLS does two things. Firstly, encrypt and verify traffic between the browser and the server. Secondly, verifying that the browser is talking to the right server. This helps to prevent attacks where someone tries to intercepts a communication between two systems.</p>

<p class="text-label<%= '--white' if defined? color %>">Label text</p>
<p class="text-caption<%= '--white' if defined? color %>">Caption text</p>

app/views/brands/show.js.erb
$('.js-current-content').html('<%= j render "/brands/#{@company}" %>')

// $(document).trigger({
//   type: "te-pageLoaded",
//   company: "<%= @company %>"
// });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <title>The Eleven Brands</title>

  <%#= stylesheet_link_tag 'application__core', media: 'all' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

<!-- asset_path does not provide the correct link on heroku
  <script id="loadcss">
    function loadCSS(e,n,o,t){"use strict";var d=window.document.createElement("link"),i=n||window.document.getElementsByTagName("script")[0],r=window.document.styleSheets;return d.rel="stylesheet",d.href=e,d.media="only x",t&&(d.onload=t),i.parentNode.insertBefore(d,i),d.onloadcssdefined=function(e){for(var n,o=0;o<r.length;o++)r[o].href&&r[o].href===d.href&&(n=!0);n?e():setTimeout(function(){d.onloadcssdefined(e)})},d.onloadcssdefined(function(){d.media=o||"all"}),d}
  </script>
  <noscript>
    <%#= stylesheet_link_tag 'application', media: 'all' %>
  </noscript>
-->

  <%= render 'shared/favicons' %>
</head>

<body>
  <div class="page-wrapper">
      <div class="nav-wrap">
        <%= render 'shared/navbar' %>

        <div class="superdupernav"></div>
      </div>

      <div class="content-wrap">
        <%= yield %>

        <%= render 'shared/footer' %>
      </div>
  </div>

  <script>
    // does not provide the correct link on heroku
    // loadCSS( "<%#= asset_path 'application.scss' %>", document.getElementById("loadcss") );
  </script>
  <%= render 'shared/scripts' %>
</body>
</html>

app/views/shared/_favicons.html.erb
<!-- remember to generate a full set of fav and app icons -->

app/views/shared/_navbar.html.erb
<%= link_to 'Brand Database', '#', class: 'nav-logo' %>

<div class="nav-container">
  <%= link_to 'Name of thing', '#', class: 'nav-link' %>
  <%= link_to 'Logo', '#', class: 'nav-link' %>
  <%= link_to 'Typography', '#', class: 'nav-link' %>
</div>

<div class="nav-mobile-links">
  <%= link_to 'Down', '#', class: 'nav-link' %>
  <%= link_to 'Contact', '#', class: 'nav-link' %>
</div>

app/views/shared/_scripts.html.erb
<%= javascript_include_tag 'application' %>

<script>
  // $(document).on('te-pageLoaded', function(event) {
  //   var company = event['company'];
  //   window.history.pushState({ site: 'The Eleven Brands' }, company, "/brands/" + company);
  // });
  //
  // window.onpopstate = function(event) {
  //   console.log(event)
  //   var popped = false;
  //
  //   if ( !popped ){
  //     location.reload()
  //     popper = true;
  //   }
  // };
</script>


<% if defined? @company %>
  <% puts "company is defined as #{@company}" %>
  <script>
    $(document).on('ready', function() {
      $.ajax({
        url: "/brands/<%= @company %>"
      })
    });
  </script>
<% else %>
  <% puts "company not defined" %>
<% end %>

<!-- Insert data tracking etc here -->

app/views/welcome/brand.html.erb
<div class="page-header page-header--mp">
  <div class="container">
    <div class="page-logo"></div>
    <h1 class="text-title">makers of brands &amp; websites for the digital age</h1>
    <p class="text-note text--center">updated at</p>
  </div>
</div>

<div class="padding bg--white">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        <p class="text-caption">Pitch</p>
      </div>
      <div class="col-xs-12 col-sm-9">
        <p class="text-body">Hi there <span class="emoji">😊</span> – This page is used for design and development</p>
      </div>
    </div>
    <%= render 'welcome/brand/iconset' %>
  </div>
</div>

<section class="padding">
  <div class="container">
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Typography – Positive</h1>
        <p class="page-subtitle">Variants of black on white</p>
      </div>
    </div>
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <%= render 'welcome/brand/typography' %>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--dark">
  <div class="container">
    <div class="row padding--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title--white">Typography – Negative</h1>
        <p class="page-subtitle--white">Variants of white on black/colour</p>
      </div>
    </div>
    <div class="row section--bottom">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <%= render 'welcome/brand/typography', color: 'white' %>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--white dev-button-variants">
  <style>.dev-button-variants .btn {margin-top: 5px;}</style>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Button Variants</h1>
        <p class="page-subtitle">Every Charlie Button</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <a href="#" class="btn">Default Button</a>
        <a href="#" class="btn btn--secondary">Secondary Button</a>
        <a href="#" class="btn btn--dark">Dark Button</a>
        <a href="#" class="btn btn--ghost">Ghost Button</a>
        <a href="#" class="btn btn--ghost-white">Ghost Button</a>
        <a href="#" class="btn btn--disabled">Disabled button</a>
        <a href="#" class="btn btn--secondary btn--disabled">Disabled button</a>
      </div>
    </div>
    <div class="row padding">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h2 class="text-lead text--center">Button special hover states:</h2>
        <a href="#" class="btn btn--to-danger">to danger</a>
      </div>
    </div>
  </div>
</section>

<section class="padding bg--dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title--white">Icon Set</h1>
        <p class="page-subtitle--white">Icons on black</p>
      </div>
    </div>
    <section class="text--white padding">
      <%= render 'welcome/brand/iconset', color: 'white' %>
    </section>
  </div>
</section>
<section class="padding">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <h1 class="section-title">Icon Set</h1>
        <p class="page-subtitle">Icons on white</p>
      </div>
    </div>
    <section class="padding">
      <%= render 'welcome/brand/iconset' %>
    </section>
  </div>
</section>

app/views/welcome/home.html.erb
<h1>Hello World</h1>

<%= link_to 'home', brands_path %>
<%= link_to 'makingpretty', brands_path(company: 'makingpretty') %>

<div class="js-current-content">
  replace me
</div>